/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_4ca6791f (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

import { createClient } from "@supabase/supabase-js";

// ✅ Use a single cached Supabase client (works in Node/Deno)
const getClient = () => {
  const url =
    Deno?.env?.get?.("SUPABASE_URL") ||
    process?.env?.SUPABASE_URL ||
    "";
  const key =
    Deno?.env?.get?.("SUPABASE_SERVICE_ROLE_KEY") ||
    process?.env?.SUPABASE_SERVICE_ROLE_KEY ||
    "";

  if (!url || !key) {
    throw new Error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
  }

  return createClient(url, key);
};

const supabase = getClient();

/* ---------------------- Single operations ---------------------- */

// Set: stores or updates a key-value pair
export const set = async (key: string, value: any): Promise<void> => {
  const { error } = await supabase.from("kv_store_4ca6791f").upsert({ key, value });
  if (error) throw new Error(`Supabase set() failed: ${error.message}`);
};

// Get: retrieves value for a given key
export const get = async (key: string): Promise<any> => {
  const { data, error } = await supabase
    .from("kv_store_4ca6791f")
    .select("value")
    .eq("key", key)
    .maybeSingle();

  if (error) throw new Error(`Supabase get() failed: ${error.message}`);
  return data?.value ?? null;
};

// Delete: removes key-value pair
export const del = async (key: string): Promise<void> => {
  const { error } = await supabase.from("kv_store_4ca6791f").delete().eq("key", key);
  if (error) throw new Error(`Supabase del() failed: ${error.message}`);
};

/* ---------------------- Batch operations ---------------------- */

// mset: sets multiple keys at once
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  if (keys.length !== values.length) {
    throw new Error("mset() requires keys and values arrays of equal length");
  }

  const entries = keys.map((k, i) => ({ key: k, value: values[i] }));
  const { error } = await supabase.from("kv_store_4ca6791f").upsert(entries);
  if (error) throw new Error(`Supabase mset() failed: ${error.message}`);
};

// mget: retrieves multiple values by keys
export const mget = async (keys: string[]): Promise<any[]> => {
  const { data, error } = await supabase
    .from("kv_store_4ca6791f")
    .select("key, value")
    .in("key", keys);

  if (error) throw new Error(`Supabase mget() failed: ${error.message}`);

  // Ensure returned values align with requested keys order
  const lookup = new Map(data.map((d) => [d.key, d.value]));
  return keys.map((k) => lookup.get(k) ?? null);
};

// mdel: deletes multiple keys
export const mdel = async (keys: string[]): Promise<void> => {
  const { error } = await supabase.from("kv_store_4ca6791f").delete().in("key", keys);
  if (error) throw new Error(`Supabase mdel() failed: ${error.message}`);
};

/* ---------------------- Search operation ---------------------- */

// getByPrefix: finds keys starting with a given prefix
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const { data, error } = await supabase
    .from("kv_store_4ca6791f")
    .select("key, value")
    .like("key", `${prefix}%`);

  if (error) throw new Error(`Supabase getByPrefix() failed: ${error.message}`);
  return data?.map((d) => d.value) ?? [];
};
